import { Inter_Tight } from "next/font/google";
import "./globals.css";
// Corrected import statement
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import Header from "@/components/ui/header";

const inter = Inter_Tight({ subsets: ["latin"] });

export const metadata = {
  title: "FinXpert",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={`${inter.className}`}>
          {/* header */}
          <Header />
          <main className="min-h-screen">{children}</main>
          <Toaster richColors />
          {/* Footer */}
          <footer className="bg-blue-200 py-12">
            <div className="container mx-auto px-4 text-center text-gray-600">
              <p>
                ©️Made With 💖 By{" "}
                <a
                  href="https://github.com/trisha3690"
                  className="text-blue-600 cursor-pointer"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Tanisha Chakraborty 
                </a>
              </p>
            </div>
          </footer>
        </body>
      </html>

  );
}
